//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHAQFWS.Core.QHDataService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/SummerFresh.WCF")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SiteDaily", Namespace="http://schemas.datacontract.org/2004/07/SummerFresh.WCF.Model")]
    [System.SerializableAttribute()]
    public partial class SiteDaily : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AQIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AreaCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string COField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CO_MarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MeasureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NO2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NO2_MarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string O3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string O3_8hField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string O3_8h_MarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string O3_MarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PM10Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PM10_MarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PM2_5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PM2_5_MarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrimaryPollutantField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QualityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SO2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SO2_MarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SiteCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SiteNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimePointField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnheathfulField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AQI {
            get {
                return this.AQIField;
            }
            set {
                if ((object.ReferenceEquals(this.AQIField, value) != true)) {
                    this.AQIField = value;
                    this.RaisePropertyChanged("AQI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Area {
            get {
                return this.AreaField;
            }
            set {
                if ((object.ReferenceEquals(this.AreaField, value) != true)) {
                    this.AreaField = value;
                    this.RaisePropertyChanged("Area");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AreaCode {
            get {
                return this.AreaCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.AreaCodeField, value) != true)) {
                    this.AreaCodeField = value;
                    this.RaisePropertyChanged("AreaCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CO {
            get {
                return this.COField;
            }
            set {
                if ((object.ReferenceEquals(this.COField, value) != true)) {
                    this.COField = value;
                    this.RaisePropertyChanged("CO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CO_Mark {
            get {
                return this.CO_MarkField;
            }
            set {
                if ((object.ReferenceEquals(this.CO_MarkField, value) != true)) {
                    this.CO_MarkField = value;
                    this.RaisePropertyChanged("CO_Mark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Measure {
            get {
                return this.MeasureField;
            }
            set {
                if ((object.ReferenceEquals(this.MeasureField, value) != true)) {
                    this.MeasureField = value;
                    this.RaisePropertyChanged("Measure");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NO2 {
            get {
                return this.NO2Field;
            }
            set {
                if ((object.ReferenceEquals(this.NO2Field, value) != true)) {
                    this.NO2Field = value;
                    this.RaisePropertyChanged("NO2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NO2_Mark {
            get {
                return this.NO2_MarkField;
            }
            set {
                if ((object.ReferenceEquals(this.NO2_MarkField, value) != true)) {
                    this.NO2_MarkField = value;
                    this.RaisePropertyChanged("NO2_Mark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string O3 {
            get {
                return this.O3Field;
            }
            set {
                if ((object.ReferenceEquals(this.O3Field, value) != true)) {
                    this.O3Field = value;
                    this.RaisePropertyChanged("O3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string O3_8h {
            get {
                return this.O3_8hField;
            }
            set {
                if ((object.ReferenceEquals(this.O3_8hField, value) != true)) {
                    this.O3_8hField = value;
                    this.RaisePropertyChanged("O3_8h");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string O3_8h_Mark {
            get {
                return this.O3_8h_MarkField;
            }
            set {
                if ((object.ReferenceEquals(this.O3_8h_MarkField, value) != true)) {
                    this.O3_8h_MarkField = value;
                    this.RaisePropertyChanged("O3_8h_Mark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string O3_Mark {
            get {
                return this.O3_MarkField;
            }
            set {
                if ((object.ReferenceEquals(this.O3_MarkField, value) != true)) {
                    this.O3_MarkField = value;
                    this.RaisePropertyChanged("O3_Mark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PM10 {
            get {
                return this.PM10Field;
            }
            set {
                if ((object.ReferenceEquals(this.PM10Field, value) != true)) {
                    this.PM10Field = value;
                    this.RaisePropertyChanged("PM10");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PM10_Mark {
            get {
                return this.PM10_MarkField;
            }
            set {
                if ((object.ReferenceEquals(this.PM10_MarkField, value) != true)) {
                    this.PM10_MarkField = value;
                    this.RaisePropertyChanged("PM10_Mark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PM2_5 {
            get {
                return this.PM2_5Field;
            }
            set {
                if ((object.ReferenceEquals(this.PM2_5Field, value) != true)) {
                    this.PM2_5Field = value;
                    this.RaisePropertyChanged("PM2_5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PM2_5_Mark {
            get {
                return this.PM2_5_MarkField;
            }
            set {
                if ((object.ReferenceEquals(this.PM2_5_MarkField, value) != true)) {
                    this.PM2_5_MarkField = value;
                    this.RaisePropertyChanged("PM2_5_Mark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrimaryPollutant {
            get {
                return this.PrimaryPollutantField;
            }
            set {
                if ((object.ReferenceEquals(this.PrimaryPollutantField, value) != true)) {
                    this.PrimaryPollutantField = value;
                    this.RaisePropertyChanged("PrimaryPollutant");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Quality {
            get {
                return this.QualityField;
            }
            set {
                if ((object.ReferenceEquals(this.QualityField, value) != true)) {
                    this.QualityField = value;
                    this.RaisePropertyChanged("Quality");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SO2 {
            get {
                return this.SO2Field;
            }
            set {
                if ((object.ReferenceEquals(this.SO2Field, value) != true)) {
                    this.SO2Field = value;
                    this.RaisePropertyChanged("SO2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SO2_Mark {
            get {
                return this.SO2_MarkField;
            }
            set {
                if ((object.ReferenceEquals(this.SO2_MarkField, value) != true)) {
                    this.SO2_MarkField = value;
                    this.RaisePropertyChanged("SO2_Mark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SiteCode {
            get {
                return this.SiteCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.SiteCodeField, value) != true)) {
                    this.SiteCodeField = value;
                    this.RaisePropertyChanged("SiteCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SiteName {
            get {
                return this.SiteNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SiteNameField, value) != true)) {
                    this.SiteNameField = value;
                    this.RaisePropertyChanged("SiteName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TimePoint {
            get {
                return this.TimePointField;
            }
            set {
                if ((this.TimePointField.Equals(value) != true)) {
                    this.TimePointField = value;
                    this.RaisePropertyChanged("TimePoint");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Unheathful {
            get {
                return this.UnheathfulField;
            }
            set {
                if ((object.ReferenceEquals(this.UnheathfulField, value) != true)) {
                    this.UnheathfulField = value;
                    this.RaisePropertyChanged("Unheathful");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CityDaily", Namespace="http://schemas.datacontract.org/2004/07/SummerFresh.WCF.Model")]
    [System.SerializableAttribute()]
    public partial class CityDaily : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AQIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string COField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CO_MarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MeasureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NO2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NO2_MarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string O3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string O3_8hField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string O3_8h_MarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string O3_MarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PM10Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PM10_MarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PM2_5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PM2_5_MarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrimaryPollutantField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QualityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SO2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SO2_MarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimePointField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnheathfulField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AQI {
            get {
                return this.AQIField;
            }
            set {
                if ((object.ReferenceEquals(this.AQIField, value) != true)) {
                    this.AQIField = value;
                    this.RaisePropertyChanged("AQI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CO {
            get {
                return this.COField;
            }
            set {
                if ((object.ReferenceEquals(this.COField, value) != true)) {
                    this.COField = value;
                    this.RaisePropertyChanged("CO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CO_Mark {
            get {
                return this.CO_MarkField;
            }
            set {
                if ((object.ReferenceEquals(this.CO_MarkField, value) != true)) {
                    this.CO_MarkField = value;
                    this.RaisePropertyChanged("CO_Mark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CityCode {
            get {
                return this.CityCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CityCodeField, value) != true)) {
                    this.CityCodeField = value;
                    this.RaisePropertyChanged("CityCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CityName {
            get {
                return this.CityNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CityNameField, value) != true)) {
                    this.CityNameField = value;
                    this.RaisePropertyChanged("CityName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Measure {
            get {
                return this.MeasureField;
            }
            set {
                if ((object.ReferenceEquals(this.MeasureField, value) != true)) {
                    this.MeasureField = value;
                    this.RaisePropertyChanged("Measure");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NO2 {
            get {
                return this.NO2Field;
            }
            set {
                if ((object.ReferenceEquals(this.NO2Field, value) != true)) {
                    this.NO2Field = value;
                    this.RaisePropertyChanged("NO2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NO2_Mark {
            get {
                return this.NO2_MarkField;
            }
            set {
                if ((object.ReferenceEquals(this.NO2_MarkField, value) != true)) {
                    this.NO2_MarkField = value;
                    this.RaisePropertyChanged("NO2_Mark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string O3 {
            get {
                return this.O3Field;
            }
            set {
                if ((object.ReferenceEquals(this.O3Field, value) != true)) {
                    this.O3Field = value;
                    this.RaisePropertyChanged("O3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string O3_8h {
            get {
                return this.O3_8hField;
            }
            set {
                if ((object.ReferenceEquals(this.O3_8hField, value) != true)) {
                    this.O3_8hField = value;
                    this.RaisePropertyChanged("O3_8h");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string O3_8h_Mark {
            get {
                return this.O3_8h_MarkField;
            }
            set {
                if ((object.ReferenceEquals(this.O3_8h_MarkField, value) != true)) {
                    this.O3_8h_MarkField = value;
                    this.RaisePropertyChanged("O3_8h_Mark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string O3_Mark {
            get {
                return this.O3_MarkField;
            }
            set {
                if ((object.ReferenceEquals(this.O3_MarkField, value) != true)) {
                    this.O3_MarkField = value;
                    this.RaisePropertyChanged("O3_Mark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PM10 {
            get {
                return this.PM10Field;
            }
            set {
                if ((object.ReferenceEquals(this.PM10Field, value) != true)) {
                    this.PM10Field = value;
                    this.RaisePropertyChanged("PM10");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PM10_Mark {
            get {
                return this.PM10_MarkField;
            }
            set {
                if ((object.ReferenceEquals(this.PM10_MarkField, value) != true)) {
                    this.PM10_MarkField = value;
                    this.RaisePropertyChanged("PM10_Mark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PM2_5 {
            get {
                return this.PM2_5Field;
            }
            set {
                if ((object.ReferenceEquals(this.PM2_5Field, value) != true)) {
                    this.PM2_5Field = value;
                    this.RaisePropertyChanged("PM2_5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PM2_5_Mark {
            get {
                return this.PM2_5_MarkField;
            }
            set {
                if ((object.ReferenceEquals(this.PM2_5_MarkField, value) != true)) {
                    this.PM2_5_MarkField = value;
                    this.RaisePropertyChanged("PM2_5_Mark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrimaryPollutant {
            get {
                return this.PrimaryPollutantField;
            }
            set {
                if ((object.ReferenceEquals(this.PrimaryPollutantField, value) != true)) {
                    this.PrimaryPollutantField = value;
                    this.RaisePropertyChanged("PrimaryPollutant");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Quality {
            get {
                return this.QualityField;
            }
            set {
                if ((object.ReferenceEquals(this.QualityField, value) != true)) {
                    this.QualityField = value;
                    this.RaisePropertyChanged("Quality");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SO2 {
            get {
                return this.SO2Field;
            }
            set {
                if ((object.ReferenceEquals(this.SO2Field, value) != true)) {
                    this.SO2Field = value;
                    this.RaisePropertyChanged("SO2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SO2_Mark {
            get {
                return this.SO2_MarkField;
            }
            set {
                if ((object.ReferenceEquals(this.SO2_MarkField, value) != true)) {
                    this.SO2_MarkField = value;
                    this.RaisePropertyChanged("SO2_Mark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TimePoint {
            get {
                return this.TimePointField;
            }
            set {
                if ((this.TimePointField.Equals(value) != true)) {
                    this.TimePointField = value;
                    this.RaisePropertyChanged("TimePoint");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Unheathful {
            get {
                return this.UnheathfulField;
            }
            set {
                if ((object.ReferenceEquals(this.UnheathfulField, value) != true)) {
                    this.UnheathfulField = value;
                    this.RaisePropertyChanged("Unheathful");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="QHDataService.IDataService")]
    public interface IDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetData", ReplyAction="http://tempuri.org/IDataService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetData", ReplyAction="http://tempuri.org/IDataService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IDataService/GetDataUsingDataContractResponse")]
        QHAQFWS.Core.QHDataService.CompositeType GetDataUsingDataContract(QHAQFWS.Core.QHDataService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IDataService/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<QHAQFWS.Core.QHDataService.CompositeType> GetDataUsingDataContractAsync(QHAQFWS.Core.QHDataService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetSiteDailyData", ReplyAction="http://tempuri.org/IDataService/GetSiteDailyDataResponse")]
        QHAQFWS.Core.QHDataService.SiteDaily[] GetSiteDailyData(System.DateTime startTime, System.DateTime endTime, int verifyState);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetSiteDailyData", ReplyAction="http://tempuri.org/IDataService/GetSiteDailyDataResponse")]
        System.Threading.Tasks.Task<QHAQFWS.Core.QHDataService.SiteDaily[]> GetSiteDailyDataAsync(System.DateTime startTime, System.DateTime endTime, int verifyState);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetSiteHoursData", ReplyAction="http://tempuri.org/IDataService/GetSiteHoursDataResponse")]
        QHAQFWS.Core.QHDataService.SiteDaily[] GetSiteHoursData(System.DateTime startTime, System.DateTime endTime, int verifyState);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetSiteHoursData", ReplyAction="http://tempuri.org/IDataService/GetSiteHoursDataResponse")]
        System.Threading.Tasks.Task<QHAQFWS.Core.QHDataService.SiteDaily[]> GetSiteHoursDataAsync(System.DateTime startTime, System.DateTime endTime, int verifyState);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetCityDailyData", ReplyAction="http://tempuri.org/IDataService/GetCityDailyDataResponse")]
        QHAQFWS.Core.QHDataService.CityDaily[] GetCityDailyData(System.DateTime startTime, System.DateTime endTime, int verifyState);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetCityDailyData", ReplyAction="http://tempuri.org/IDataService/GetCityDailyDataResponse")]
        System.Threading.Tasks.Task<QHAQFWS.Core.QHDataService.CityDaily[]> GetCityDailyDataAsync(System.DateTime startTime, System.DateTime endTime, int verifyState);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetCityHoursData", ReplyAction="http://tempuri.org/IDataService/GetCityHoursDataResponse")]
        QHAQFWS.Core.QHDataService.CityDaily[] GetCityHoursData(System.DateTime startTime, System.DateTime endTime, int verifyState);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetCityHoursData", ReplyAction="http://tempuri.org/IDataService/GetCityHoursDataResponse")]
        System.Threading.Tasks.Task<QHAQFWS.Core.QHDataService.CityDaily[]> GetCityHoursDataAsync(System.DateTime startTime, System.DateTime endTime, int verifyState);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDataServiceChannel : QHAQFWS.Core.QHDataService.IDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataServiceClient : System.ServiceModel.ClientBase<QHAQFWS.Core.QHDataService.IDataService>, QHAQFWS.Core.QHDataService.IDataService {
        
        public DataServiceClient() {
        }
        
        public DataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public QHAQFWS.Core.QHDataService.CompositeType GetDataUsingDataContract(QHAQFWS.Core.QHDataService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<QHAQFWS.Core.QHDataService.CompositeType> GetDataUsingDataContractAsync(QHAQFWS.Core.QHDataService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public QHAQFWS.Core.QHDataService.SiteDaily[] GetSiteDailyData(System.DateTime startTime, System.DateTime endTime, int verifyState) {
            return base.Channel.GetSiteDailyData(startTime, endTime, verifyState);
        }
        
        public System.Threading.Tasks.Task<QHAQFWS.Core.QHDataService.SiteDaily[]> GetSiteDailyDataAsync(System.DateTime startTime, System.DateTime endTime, int verifyState) {
            return base.Channel.GetSiteDailyDataAsync(startTime, endTime, verifyState);
        }
        
        public QHAQFWS.Core.QHDataService.SiteDaily[] GetSiteHoursData(System.DateTime startTime, System.DateTime endTime, int verifyState) {
            return base.Channel.GetSiteHoursData(startTime, endTime, verifyState);
        }
        
        public System.Threading.Tasks.Task<QHAQFWS.Core.QHDataService.SiteDaily[]> GetSiteHoursDataAsync(System.DateTime startTime, System.DateTime endTime, int verifyState) {
            return base.Channel.GetSiteHoursDataAsync(startTime, endTime, verifyState);
        }
        
        public QHAQFWS.Core.QHDataService.CityDaily[] GetCityDailyData(System.DateTime startTime, System.DateTime endTime, int verifyState) {
            return base.Channel.GetCityDailyData(startTime, endTime, verifyState);
        }
        
        public System.Threading.Tasks.Task<QHAQFWS.Core.QHDataService.CityDaily[]> GetCityDailyDataAsync(System.DateTime startTime, System.DateTime endTime, int verifyState) {
            return base.Channel.GetCityDailyDataAsync(startTime, endTime, verifyState);
        }
        
        public QHAQFWS.Core.QHDataService.CityDaily[] GetCityHoursData(System.DateTime startTime, System.DateTime endTime, int verifyState) {
            return base.Channel.GetCityHoursData(startTime, endTime, verifyState);
        }
        
        public System.Threading.Tasks.Task<QHAQFWS.Core.QHDataService.CityDaily[]> GetCityHoursDataAsync(System.DateTime startTime, System.DateTime endTime, int verifyState) {
            return base.Channel.GetCityHoursDataAsync(startTime, endTime, verifyState);
        }
    }
}
